language: node_js
sudo: required
node_js:
  - '8'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - export CHROME_BIN=/usr/bin/google-chrome
env:
  - TEST_SUITE=test:karma
  - TEST_SUITE=test:protractor
  ## Runs all tests:
  # - TEST_SUITE=test
script:
  - npm run $TEST_SUITE
addons:
  chrome: stable
