language: node_js
sudo: required
node_js:
  - '8'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - export CHROME_BIN=/usr/bin/google-chrome
  - npm run start:webdriver
script:
  - npm test
  - npm run start &
  - sleep 3 # give http-server some time to start
  - npm run test:protractor
addons:
  chrome: stable
  firefox: latest